name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          deploy_key: ${{ secrets.ACCESS_TOKEN }}
          publish_branch: gh-pages
          publish_dir: .
          cname: www.emanuelemacera.com
          custom_domain: www.emanuelemacera.com
          ssl_cert: ${{ secrets.SSL_CERT }}
          ssl_key: ${{ secrets.SSL_KEY }}
          ca_bundle: ${{ secrets.CA_BUNDLE }}
